controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    arm_group_controller:
      type: forward_command_controller/ForwardCommandController
      # type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - robot1_J1
      - robot1_J2
      - robot1_J3
      - robot1_J4
      - robot1_J5
      - robot1_J6
    interface_name: effort
