controller_manager:
  ros__parameters:
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - robot1_arm_j1
        - robot1_arm_j2
        - robot1_arm_j3
        - robot1_arm_j4
        - robot1_arm_j5
        - robot1_arm_j6
      interface_name: position

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster